# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6019cdc29d924440a10210a08142b0318dfdd4ff44fb6931bd364d1915b1d4382a3e3877eb3e4a93b86f2ea63afda4aa53af4ae446b4b8be274403ebea4745b2

test:
  secret_key_base: f5f5a5bb6d7180e1459d094130bcfa6301c5d24a038ee54791a5393a549964d440361102cccb4f4fd3e1b4743e2362b159f2fededfd372aeb495fec200fe901e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
